### Gerando access token (Direct Grant ou Resource Owner Password Credentials Grant)
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=user@user.com
&password=secret
&grant_type=password
&client_id=fullcycle-client

### Gerando access token e id token
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=user@user.com
&password=secret
&grant_type=password
&client_id=fullcycle-client
&scope=openid


### authorization code flow
POST http://localhost:8080/realms/fullcycle-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id=fullcycle-client
&code=0bdf618a-4591-4c5b-87dd-1aa44f037a1f.c8129f0e-eaaf-45c0-b37f-d1985799b0a0.b10f908f-5d45-408f-8b64-40fea4bd0b13
&redirect_uri=http://localhost:3000/callback
